server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.217.138:3306/match?characterEncoding=utf-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&autoReconnect=true&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false
    username: root
    password: ewdsG87few
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 8 #最小空闲连接数量
      maximum-pool-size: 16 #连接池最大连接数，默认是10
      idle-timeout: 30000 #空闲连接存活最大时间，默认600000（10分钟）
      auto-commit: true #控制从池返回的链接的默认自动提交行为，默认值：true
      pool-name: MyMarketJobHikariCP #连接池母子
      max-lifetime: 120000 #控制池中链接的最长生命周期，值0表示无限生命周期，默认1800000，即30分钟
      connection-timeout: 30000 #数据库链接超时时间，默认30秒，即30000
      connection-test-query: SELECT 1